version: "3.9"

services:
  jetstream:
    container_name: nats-cluster
    image: nats:latest
    entrypoint: /nats-server
    ports:
      - "4222:4222"
    command: --name nats --cluster_name NATS --js --sd /data -p 4222

  agent:
    container_name: "agent-container"
    build:
      context: .
      dockerfile: Dockerfile
    command: agent
    volumes:
      - "./config/config.example.yaml:/app/config.yml"
    ports:
      - "8080:8080"
    depends_on:
      - jetstream
    networks:
      - jester

  consumer:
    container_name: "consumer-container"
    build:
      context: .
      dockerfile: Dockerfile
    command: consumer
    volumes:
      - "./config/config.example.yaml:/app/config.yml"
    depends_on:
      - agent
    networks:
      - jester

  publisher:
    container_name: "consumer-container"
    build:
      context: .
      dockerfile: Dockerfile
    command: publisher
    volumes:
      - "./config/config.example.yaml:/app/config.yml"
    depends_on:
      - agent
    networks:
      - jester

networks:
  jester:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.255.0/24
      driver: default
